# Site settings
title: "HongXu Ke's Resume"
description: "HongXu Ke's | Experienced Shopify developer"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "柯洪旭 | HoneXu Ke"
resume_title:                   "Shopify Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "khx9468@123.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "15141589468"
resume_contact_address:         "Liaoning, Dandong, Jinxing, 1-1"

resume_header_contact_info:     "Liaoning, Dandong, Jinxing, 1-1 • 15141589468 • khx9468@123.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a Shopify developer, I was lucky to work with life leading brands and companies such as Half Helix, Logo Media, MackWeldon, K2awards ...</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jewelltl/jewelltl"
  resume_linkedin_url:          "https://www.linkedin.com/in/hongxu-ke"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
